### ISSUE TITLE
Integration tests throw multiple ServiceConfigurationErrors for OWL API classes

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-server#13]
This happens with the latest update to OWL API 4.1.3 in commit 429f29e.

    23:26:37.377 [FelixStartLevel] DEBUG o.s.owlapi.OWLAPIServiceLoaderModule - ServiceLoading: 
    java.util.ServiceConfigurationError: org.semanticweb.owlapi.model.OWLDocumentFormatFactory: Provider org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory not a subtype
    	at java.util.ServiceLoader.fail(ServiceLoader.java:239) ~[na:1.8.0_25]
    	at java.util.ServiceLoader.access$300(ServiceLoader.java:185) ~[na:1.8.0_25]
    	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376) ~[na:1.8.0_25]
    	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_25]
    	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_25]
    	at com.google.common.collect.Iterators.addAll(Iterators.java:362) ~[guava-18.0.jar:na]
    	at com.google.common.collect.Iterables.addAll(Iterables.java:354) ~[guava-18.0.jar:na]
    	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.load(OWLAPIServiceLoaderModule.java:87) ~[owlapi-osgidistribution-4.1.3.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadFactories(OWLAPIServiceLoaderModule.java:109) ~[owlapi-osgidistribution-4.1.3.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(OWLAPIServiceLoaderModule.java:58) ~[owlapi-osgidistribution-4.1.3.jar:4.1.3.20151118-2017]
    	at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
    	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
    	at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
    	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.0.jar:na]
    	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.0.jar:na]
    	at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0.jar:na]
    	at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.0.jar:na]
    	at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.0.jar:na]
    	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:89) ~[owlapi-osgidistribution-4.1.3.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:97) ~[owlapi-osgidistribution-4.1.3.jar:4.1.3.20151118-2017]
    	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58) ~[owlapi-osgidistribution-4.1.3.jar:4.1.3.20151118-2017]
    	at org.protege.owl.server.Activator.loadConfiguration(Activator.java:45) ~[classes/:na]
    	at org.protege.owl.server.Activator.start(Activator.java:28) ~[classes/:na]
    	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645) ~[org.apache.felix.main-4.4.1.jar:na]
    	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2154) ~[org.apache.felix.main-4.4.1.jar:na]
    	at org.apache.felix.framework.Felix.startBundle(Felix.java:2072) ~[org.apache.felix.main-4.4.1.jar:na]
    	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299) ~[org.apache.felix.main-4.4.1.jar:na]
    	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304) ~[org.apache.felix.main-4.4.1.jar:na]
    	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_25]
    23:26:37.398 [FelixStartLevel] DEBUG o.s.owlapi.OWLAPIServiceLoaderModule - ServiceLoading: 
    java.util.ServiceConfigurationError: org.semanticweb.owlapi.io.OWLParserFactory: Provider org.semanticweb.owlapi.rio.RioBinaryRdfParserFactory not a subtype
    ...
    java.util.ServiceConfigurationError: org.semanticweb.owlapi.io.LegacyOWLParserFactory: Provider org.coode.owlapi.obo12.parser.OBO12ParserFactory not a subtype
    ...
    java.util.ServiceConfigurationError: org.semanticweb.owlapi.model.OWLStorerFactory: Provider org.semanticweb.owlapi.rio.RioBinaryRdfStorerFactory not a subtype
    ...
    java.util.ServiceConfigurationError: org.semanticweb.owlapi.model.OWLOntologyManagerFactory: Provider org.semanticweb.owlapi.apibinding.OWLManager not a subtype
    ...
    java.util.ServiceConfigurationError: org.semanticweb.owlapi.io.LegacyOWLParserFactory: Provider org.coode.owlapi.obo12.parser.OBO12ParserFactory not a subtype
    ......

**Comment by johardi** [comment]
The issue is no longer relevant
