### ISSUE TITLE
Protege server does not initialize after latest commits

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-server#27]
I get the following when I try to start the server after updating to the latest state of the http branch.

    java.lang.NullPointerException
    	at org.protege.editor.owl.server.security.SSLContextFactory.loadKeyStore(SSLContextFactory.java:63)
    	at org.protege.editor.owl.server.security.SSLContextFactory.createSslContext(SSLContextFactory.java:43)
    	at org.protege.editor.owl.server.http.HTTPServer.start(HTTPServer.java:214)
    	at org.protege.editor.owl.server.http.HTTPServer.main(HTTPServer.java:109)
    Exception in thread "main" java.lang.NullPointerException
    	at org.protege.editor.owl.server.http.HTTPServer.start(HTTPServer.java:236)
    	at org.protege.editor.owl.server.http.HTTPServer.main(HTTPServer.java:109)

**Comment by bdionne** [comment]
Yes, the server now uses the [scheme](https://github.com/protegeproject/protege-server/commit/8afaa405a1aaf5b8258) from the host url in the config file to distinguish whether to use an http or https listener. Changing the url in your config file should make it work. I put this in to make testing easier.

**Comment by rsgoncalves** [comment]
I currently have https, as in:
    "host": { "uri": "https://localhost:8080" }

**Comment by rsgoncalves** [comment]
When I switch to "http" it works well 👍

**Comment by bdionne** [comment]
it also works with https but you'll need a self-signed cert, a java keystore, and pass some properties in to the JVM
